version: "3"

services:
  aws:
    container_name: aws
    image: minio/minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET}
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - aws:/data
    command: server /data --console-address ":9090"

  aws-init:
    container_name: aws-init
    image: minio/mc
    depends_on:
      - aws
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/bin/mc alias set myminio http://aws:9000 ${S3_ACCESS_KEY_ID} ${S3_SECRET};
        /usr/bin/mc mb myminio/${S3_BUCKET};
        /usr/bin/mc policy set public myminio/${S3_BUCKET};

  db:
    container_name: db
    image: mysql:8
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - db:/var/lib/mysql
    working_dir: /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1

volumes:
  aws:
  db:
