version: "3"

services:
  minio:
    container_name: minio
    image: minio/minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET}
    ports:
      - ${S3_PORT}:${S3_PORT}
      - 9090:9090
    volumes:
      - minio:/data
    command: server /data --console-address ":9090"

  minio-init:
    container_name: minio-init
    image: minio/mc
    depends_on:
      - minio
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/bin/mc config host add docker http://minio:${S3_PORT} ${S3_ACCESS_KEY_ID} ${S3_SECRET};
        /usr/bin/mc mb docker/${S3_BUCKET};
        /usr/bin/mc anonymous set public docker/${S3_BUCKET};

  db:
    container_name: db
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - db:/var/lib/mysql
    working_dir: /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1

volumes:
  minio:
  db:
