version: "3"

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - aws
      - db
