name: Deploy Host (dev)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH remote commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEVHOST_HOST }}
          username: ${{ secrets.DEVHOST_USERNAME }}
          key: ${{ secrets.DEVHOST_KEY }}
          script: sh /home/deploy.sh
